version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=local
    ports:
      - "8000:8000"
    depends_on:
      - db  # Ensure app waits for db container
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storage_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
volumes:
  postgres_data:
